export enum SituacaoPedido{
    EM_ABERTO = "EM_ABERTO",
    EM_ATENDIMENTO = "EM_ATENDIMETO",
    EM_PRODUCAO = "EM_PROCESSO",
    EM_PROCESSO_DE_ENTREGA = "EM_PROCESSO_DE_ENTREGA",
    ENTREGUE = "ENTREGUE",
    FINALIZADO = "FINALIZADO"
}